.TH RUNOVERSSH 1
.SH NAME
runoverssh \- POSIX-compliant shell script for easily running shell commands and scripts over SSH
.SH SYNOPSIS
.B runoverssh
[\fBOPTIONS\fR]
USERNAME
COMMAND
HOSTS...
.SH DESCRIPTION
.B runoverssh
POSIX-compliant shell script for easily running shell commands and scripts over SSH.
.SH OPTIONS
.TP
.BR \-g ", " \-\-globalpw
Prompt a global password for all connections

.TP
.BR \-s ", " \-\-script " " [file]
Read commands from a script file, disables the default COMMAND argument

.TP
.BR \-r ", " \-\-hostsfile " " [file]
Read the list of hosts from a file (one host per line), disables the default HOSTS argument

.TP
.BR \-a ", " \-\-args " " [args]
Arguments (in a single string) to be passed to the script file.

.TP
.BR \-q ", " \-\-quiet " "
Disable all screen output, except for password prompts. If logfile is set, output is written there

.TP
.BR \-v ", " \-\-verbose " "
Print verbose messages

.TP
.BR \-\-shell " " [shell]
Remote shell to be used.
Supported values: sh, bash.
Default: bash

.TP
.BR \-\-shellflags " " [shellflags]
Remote shell flags.
Default: ''

.TP
.BR \-\-sshflags " " [shellflags]
Local SSH flags.
Default: -o ConnectTimeout=5
         -o StrictHostKeyChecking=no
         -o UserKnownHostsFile=/dev/null

.TP
.BR \-\-logfile " " [file]
Append SSH output to a file

.SH AUTHOR
runoverssh was written by Yuri Escalianti.

